# Generated by Django 3.0.7 on 2020-06-09 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, verbose_name='Descrição')),
                ('source', models.GenericIPAddressField(verbose_name='Origem')),
                ('details', models.TextField(verbose_name='Detalhes')),
                ('events', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Eventos')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('level', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('DEBUG', 'DEBUG'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO')], max_length=16, verbose_name='Level')),
                ('env', models.CharField(choices=[('PRODUÇÃO', 'PRODUÇÃO'), ('HOMOLOGAÇÃO', 'HOMOLOGAÇÃO'), ('DEV', 'DEV')], max_length=16, verbose_name='Ambiene')),
                ('arquivado', models.BooleanField(default=False, verbose_name='Arquivado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Error Log',
            },
        ),
    ]
