# Generated by Django 3.0.7 on 2020-06-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlog',
            old_name='arquivado',
            new_name='archived',
        ),
    ]
