# Generated by Django 3.0.7 on 2020-06-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200610_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='env',
            field=models.CharField(choices=[('production', 'PRODUÇÃO'), ('homologation', 'HOMOLOGAÇÃO'), ('dev', 'DEV')], max_length=16, verbose_name='Ambiene'),
        ),
    ]
