# Generated by Django 3.0.7 on 2020-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200611_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='env',
            field=models.CharField(choices=[('PRODUCTION', 'PRODUÇÃO'), ('HOMOLOGATION', 'HOMOLOGAÇÃO'), ('DEV', 'DEV')], max_length=16, verbose_name='Ambiene'),
        ),
    ]
