# Generated by Django 3.0.7 on 2020-06-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200611_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='env',
            field=models.CharField(choices=[('PRODUCTION', 'PRODUCTION'), ('HOMOLOGATION', 'HOMOLOGATION'), ('DEV', 'DEV')], max_length=16, verbose_name='Ambiene'),
        ),
    ]
