# Generated by Django 3.0.7 on 2020-06-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200611_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Error Log'},
        ),
    ]
