# Generated by Django 3.0.7 on 2020-06-03 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128, verbose_name='origem')),
                ('events', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='eventos')),
                ('details', models.TextField(verbose_name='detalhes')),
                ('description', models.CharField(max_length=256, verbose_name='descrição')),
                ('raised_at', models.DateTimeField(verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'log de erro',
                'verbose_name_plural': 'logs de erro',
            },
        ),
    ]
